services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://prism:4010
    volumes:
      - .:/app
    command: npm run dev:next

  mock-api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npx json-server --watch db.json --port 3001"
    ports:
      - "3001:3001"

  prism:
    image: stoplight/prism:4
    command: proxy /tmp/user-api.yaml http://mock-api:3001 --cors --errors --port 4010
    ports:
      - "4010:4010"
    depends_on:
      - mock-api
    volumes:
      - ./openapi:/tmp
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4010"]
      interval: 5s
      timeout: 3s
      retries: 10

