version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://prism:4010
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev:next
    depends_on:
      - prism

  mock-api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npx json-server --watch db.json --port 3001"
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  prism:
    image: stoplight/prism:4
    command: proxy /tmp/user-api.yaml http://mock-api:3001 --cors --errors --port 4010
    ports:
      - "4010:4010"
    depends_on:
      mock-api:
        condition: service_healthy
    volumes:
      - ./openapi:/tmp
